// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0PZ7OXLtjo6Ms9iCl4TOv4GBipGV9oSc',
    appId: '1:705668070834:web:6eda3d88624c2d9c68f8ab',
    messagingSenderId: '705668070834',
    projectId: 'chat-application-55c82',
    authDomain: 'chat-application-55c82.firebaseapp.com',
    storageBucket: 'chat-application-55c82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG518NrYwfJhEswIns-bdIalJqYPLTJOI',
    appId: '1:705668070834:android:00b1be3dee0aa40a68f8ab',
    messagingSenderId: '705668070834',
    projectId: 'chat-application-55c82',
    storageBucket: 'chat-application-55c82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3UVTacpjoFF_PMJRbad1-n6xi0OW8xpo',
    appId: '1:705668070834:ios:d2755b816548052768f8ab',
    messagingSenderId: '705668070834',
    projectId: 'chat-application-55c82',
    storageBucket: 'chat-application-55c82.appspot.com',
    androidClientId: '705668070834-87ef3kpq59tqgqa5im8fjafa9skl7mrl.apps.googleusercontent.com',
    iosClientId: '705668070834-fbo56b941lah4ugq6tjo33nhigu1a6vq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3UVTacpjoFF_PMJRbad1-n6xi0OW8xpo',
    appId: '1:705668070834:ios:d2755b816548052768f8ab',
    messagingSenderId: '705668070834',
    projectId: 'chat-application-55c82',
    storageBucket: 'chat-application-55c82.appspot.com',
    androidClientId: '705668070834-87ef3kpq59tqgqa5im8fjafa9skl7mrl.apps.googleusercontent.com',
    iosClientId: '705668070834-fbo56b941lah4ugq6tjo33nhigu1a6vq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
