// Mocks generated by Mockito 5.4.0 from annotations
// in chat_app/test/features/auth/domain/usecases/login_user_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chat_app/core/error/failures.dart' as _i5;
import 'package:chat_app/features/auth/domain/entitites/user.dart' as _i7;
import 'package:chat_app/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:chat_app/features/auth/domain/usecases/login_user.dart' as _i8;
import 'package:chat_app/features/auth/domain/usecases/register_user.dart'
    as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> registerUser(
          _i6.RegisterUserParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #registerUser,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.User>> loginUser(
          _i8.LoginUserParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginUser,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.User>>.value(
            _FakeEither_0<_i5.Failure, _i7.User>(
          this,
          Invocation.method(
            #loginUser,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.User>>);
}
